Filling out TBD sections in chapter 4.
cncf/sig-app-delivery pull request #102
Opened 2021-03-26 05:34 UTC by jlk

2021-03-26 10:15 UTC, OmerKahani approved these changes

2021-03-27 07:04 UTC, thschue commented on operator-wg/whitepaper-community-review/README.md
>  During development of an operator you should have a clear understanding
```suggestion
During development of an operator a developer should have a clear understanding
```

2021-03-27 07:05 UTC, thschue commented on operator-wg/whitepaper-community-review/README.md
> +have a clear understanding of what your operator does, and how.
```suggestion
have a clear understanding of what the operator does, and how.
```

2021-03-27 07:06 UTC, thschue commented on operator-wg/whitepaper-community-review/README.md
> +from development to publishing your work, your users should also
```suggestion
from development to publishing the work (operator), users should also
```

2021-03-27 07:06 UTC, thschue commented on operator-wg/whitepaper-community-review/README.md
> +Anything you can do to help this (probably busy) person come up to
Change to third person voice ...

2021-03-27 07:09 UTC, thschue requested changes
Please change to third person voice as far as possible ...

2021-03-27 07:09 UTC, thschue commented on operator-wg/whitepaper-community-review/README.md
> +* If your project has had security disclosures in the past, listing
```suggestion
* If the project has had security disclosures in the past, listing
```

2021-03-27 07:09 UTC, thschue commented on operator-wg/whitepaper-community-review/README.md
> +in building trust with your users. Everyone will have security
```suggestion
in building trust with users. Everyone will have security
```

2021-03-27 07:09 UTC, thschue commented on operator-wg/whitepaper-community-review/README.md
> +issues at some point - how you handle them displays the maturity
```suggestion
issues at some point - how they are handled displays the maturity
```

2021-03-27 07:09 UTC, thschue commented on operator-wg/whitepaper-community-review/README.md
> +work on it will make this process much easier for you and your
```suggestion
work on it will make this process much easier for developers and their
```

2021-03-30 21:27 UTC, jlk commented on operator-wg/whitepaper-community-review/README.md
> +Anything you can do to help this (probably busy) person come up to
done

2021-03-31 06:27 UTC, merged