Draft: make it more k8s agnostic
cncf/sig-app-delivery pull request #70
Opened 2021-03-02 18:24 UTC by Jenniferstrej

2021-03-15 21:11 UTC, OmerKahani approved these changes

2021-03-16 06:23 UTC, thschue requested changes

2021-03-16 06:23 UTC, thschue commented on operator-wg/whitepaper/02_Foundation.md
> +The core purpose of any operator is to extend its orcherstrator's underlying API with new domain knowledge. For instance, just like Kubernetes natively understands things like containers and layer 4
```suggestion
The core purpose of any operator is to extend its orchestrator's underlying API with new domain knowledge. As an example, an orchestration platform as Kubernetes natively understands things like containers and layer 4 load balancers via the Pod and Service objects. An operator adds new capabilities for more complex systems and applications. For instance, a prometheus-operator introduces new object types, "Prometheus", which extend Kubernetes with high-level support for deploying and running Prometheus servers.
```

2021-03-18 05:31 UTC, thschue approved these changes
lgtm

2021-03-18 05:31 UTC, merged