feat: use cases - Prometheus
cncf/sig-app-delivery pull request #90
Opened 2021-03-15 20:32 UTC by Jenniferstrej

2021-03-15 21:13 UTC, OmerKahani approved these changes

2021-03-16 06:28 UTC, thschue requested changes

2021-03-16 06:28 UTC, thschue commented on operator-wg/whitepaper/07_Use_Cases.md
> +When you install the [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md), besides the operator controller pod/de
```suggestion
When the [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md) is installed besides the operator controller pod/deployment, a wide range of APIs gets available to configure a Prometheus stack. The APIs are represented as Custom Resource Definitions (CRDs) which allow to configure objects responsible, among other tasks, for:
```

2021-03-16 09:19 UTC, thschue approved these changes

2021-03-16 09:34 UTC, thschue approved these changes

2021-03-16 10:03 UTC, merged